{% set name = "plac" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f05bf85235c017fcd76c73c8101d4ff8e96beb3dc58b9a37de49cac7de82d14

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - doc/test_plac.py
  imports:
    - plac
    - plac_core
    - plac_ext
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest doc/test_plac.py -v -k "not test_doctest"

about:
  home: https://github.com/ialbert/plac
  license: BSD-2-Clause
  license_family: BSD
  summary: The smartest command line arguments parser in the world
  doc_url: https://plac.readthedocs.io
  dev_url: https://github.com/ialbert/plac

extra:
  recipe-maintainers:
    - pmlandwehr
