{% set name = "plac" %}
{% set version = "1.2.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "ca03587234e5bdd2a3fa96f19a04a01ebb5b0cd66d48ecb5a54d42bc9b287320" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - plac

about:
  home: https://micheles.github.io/plac/
  # license_file: No license yet - see https://github.com/micheles/plac/issues/26
  license: BSD 2-Clause
  license_family: BSD
  summary: 'The smartest command line arguments parser in the world'
  doc_url: https://micheles.github.io/plac/
  dev_url: https://github.com/micheles/plac

extra:
  recipe-maintainers:
    - pmlandwehr
