travis:
  secure:
    BINSTAR_TOKEN: exyi8MLhevF3lK6emOqG7cbj03/yMEr71Lcu5LP07FIYHv6MyFXh6vSNld3zRR/mspeD3nXj94h4ofJjCYgHBkHkF9LnBmSk0FxWB3d30rE63ExwE9hxZVOI64bG1PCiS7+WfEXJDo7VrXki3W4bTKAU3E0NxbXrVgzabF/Te1R3visDDlNsAuXzjFIbst/jfFDM/FZoNyvE3mLpoQP+2D+y8aRlXuQJe71DnSBYsmWGvCQLtcZOA9pdd6xg+MCv5BHnSPlbrGWS3F3K8KlVXhUk+InQbUubfTKW4FIn9o3vBp5fd4qKaL/VZC8nu8kV5kETXur916gIXGTcSufpVI6arpSIFPWTQlVo8EJAZdOEZG6LHAeHN44JFfEdMQ/GORJLVV7/GaTi7s96VaNzJitgSz64bAoknBxiGJ6Sji9G/BpMNPT8YEPDZsR9ONvscC5kT9tcb1pS8N2F/wJ4iTpeIUTlBxS7MvrtyZubWiZOxu+V5bNqsry1hn73YL3nPKyA+g2QEKu1ykuwuIEmiqeeOzYYHVIg9+mop6QYg6HeRk+qa1rTLRR9acIDR7XX+LhTNl8bxWZcEKsYDLCQeaiknadPkrB/V5Eh37m/inyvL0XZdWoDOHIjiHYpxZnq9XIdwAiF9lTp0whQnKlwlcA5m6fyYpRMO38H0d6fw30=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
